ESTADOS = {
    "INICIO": "INICIO",
    "CONFIGURANDO_MOVEL": "CONFIGURANDO_MOVEL",

    "ESCOLHER_DIMENSAO": "ESCOLHER_DIMENSAO",
    "ALTERAR_DIMENSAO": "ALTERAR_DIMENSAO",

    "ESCOLHER_COR": "ESCOLHER_COR",
    "ESCOLHER_MATERIAL": "ESCOLHER_MATERIAL",

    "ESCOLHER_CATEGORIA_COMPONENTE": "ESCOLHER_CATEGORIA_COMPONENTE",
    "ESCOLHER_COMPONENTE": "ESCOLHER_COMPONENTE",

    "CONFIRMACAO_FINAL": "CONFIRMACAO_FINAL",
}